//defines.h

#define WRITEBYTE(WORD,BYTESTARTBITPOS,VAL) \
         WORD=((WORD&~(255<<BYTESTARTBITPOS))|(VAL<<BYTESTARTBITPOS)) 
#define WRITENIBBLE(WORD,BYTESTARTBITPOS,VAL) \
         WORD=((WORD&~(15<<BYTESTARTBITPOS))|((VAL&15)<<BYTESTARTBITPOS))
#define READNIBBLE(WORD,BYTESTARTBITPOS) \
         (( WORD>>BYTESTARTBITPOS)&15)
#define READBIT(WORD,BIT) \
        ((WORD>>BIT)&1)
